server:
  port: 8082

spring:
  application:
    name: stock-service
  config:
    import: optional:file:.env[.properties]

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  docker:
    compose:
      file: docker-compose.yaml
      lifecycle-management: start_only
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6435/${STOCK_SERVICE_DB_NAME}
    username: ${STOCK_SERVICE_DB_USER}
    password: ${STOCK_SERVICE_DB_PASSWORD}
  data:
    jpa:
      repositories:
        enabled: true