server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: optional:file:.env[.properties]

  cloud:
    stream:
      bindings:
        output:
          destination: order-service.order.created.topic
        input:
          destination: payment-service.payment.status.exchange.topic
      kafka:
        binder:
          brokers:
            - localhost:9092
            - localhost:9094
            - localhost:9096
            - localhost:9098
            - localhost:9100

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    database: postgresql
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:6433/${ORDER_SERVICE_DB_NAME}
    username: ${ORDER_SERVICE_DB_USER}
    password: ${ORDER_SERVICE_DB_PASSWORD}
  data:
    jpa:
      repositories:
        enabled: true