-- liquibase formatted sql

-- changeset Torchez:1726510790142-1
CREATE TABLE items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stock_id     UUID,
    product_type VARCHAR(255),
    quantity     INTEGER,
    cost         DECIMAL,
    order_id_id  BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

-- changeset Torchez:1726510790142-2
CREATE TABLE orders
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id      BIGINT,
    total_amount     DECIMAL,
    order_date       date,
    last_update_date TIMESTAMP WITHOUT TIME ZONE,
    order_status     VARCHAR(255),
    payment_status   VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

-- changeset Torchez:1726510790142-3
ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_ORDERID FOREIGN KEY (order_id_id) REFERENCES orders (id);

